### PR TITLE
Scrapy Startup

### PR DESCRIPTION
**Pull request by LennoxHB**
Created a scrapy project in the root. So far I've been trying to get it to work dynamically in a domain supplied by the user, so at the moment it crawls through all interrnal links and records all links to a .json file.

To run the spider:
1. `cd scraper`
2. `scrapy crawl spider -O links.json -a url=<DOMAIN>`

Domain example: quotes.toscrape.com
do not include www / https, etc.

# Useful:
To use scrapy in git bash:
1. Install Anaconda Python
2. Find where conda.sh is, probably: C:\Users\<USER>\anaconda3\etc\profile.d
3. Open Git Bash in the folder.
4. Enter `PWD`
5. Enter `echo ". ${PWD}/conda.sh" >> ~/.bashrc`
6. Reopen the terminal.
7. Enter `conda activate`
8. Now you can use scrapy or anything conda related in git bash terminal.

### CODE REVIEW

**Review by ALADM2 — APPROVED** [review]
Good guide on how to use it. It works perfectly.

**Comment by ALADM2** [comment]
I guess next step is to get the text and somehow count words.
I know you can take the text with this code but it seems to get some of them more than once. Also, I'm not sure yet how to count words the right way.

        for quote in response.css('div.quote'):
            yield {
                'text': quote.css('span.text::text').get(),
            }

**Comment by LennoxHB** [comment]
> I guess next step is to get the text and somehow count words. I know you can take the text with this code but it seems to get some of them more than once. Also, I'm not sure yet how to count words the right way.
> 
> ```
>     for quote in response.css('div.quote'):
>         yield {
>             'text': quote.css('span.text::text').get(),
>         }
> ```

**Comment by LennoxHB** [comment]
I think what we want to do is get all the body text, something like div.quote isn't going to work on a lot of sites, since its probably not common to use quote as a class attribute. Then I'm guessing we can send it to our backend or other program, process the text to extract common words and upload the processed data to our DB, to then be read by our frontend application.

**Comment by ALADM2** [comment]
Sure. That example is just for the page provided by the tutorial.

**Pull request merged**
