### PR TITLE
Login system

### LINKED ISSUE #23: Improve login system
Add functionality to allow users to login using their Google, Twitter or Facebook accounts.

### PR DESCRIPTION
**Pull request by abdallah-altay**
Added functionally to let users login using their social media accounts. (Google, Facebook, GitHub) Fixes #23 

Implemented using [Passport.js](https://www.passportjs.org/) authentication middleware.
Add controller for passport setup and routes for OAuth.
Update user model to save users who login through social media account into mongodb.
Update .env files to allow automatically setting URLs etc. based on environment.
Refactor login context on frontend to fetch currently logged in user.
Display social media login options on login and register pages.

### CODE REVIEW

**Review by ALADM2 — APPROVED** [review]
Works great. It logs in with different social media and it looks good in the front end.

**Review by ALADM2 — CHANGES_REQUESTED** [review]
Very good work. Google and Github login work. Facebooks still have some issue in my end, I hope is easy to fix. 

image

**Comment by abdallah-altay** [comment]
The Facebook app is taking a while to get activated/approved, so still waiting on that to let non-admin/dev users login with it. We could probably just remove the Facebook login feature and when it's working we can put it back in.
That way we can at least get the Google/GitHub login on production since they are working fine. What do you think ? @ALADM2

**Comment by ALADM2** [comment]
Yes I agree, let's just do that and add facebook login at some other point.

**Review by ALADM2 — APPROVED** [review]

**Pull request merged**
